apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}-success-rate-check
spec:
  args:
    - name: canary-hash
  metrics:
    - name: success-rate
      interval: 60s
      count: 3              # run 3 times
      successCondition: result[0] >= 0.95   # 95%+ success rate required
      failureLimit: 1       # fail immediately if any check fails
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(rate(http_requests_total{
              app="{{ .Release.Name }}",
              status!~"5..",
              rollouts_pod_template_hash="{{ "{{ args.canary-hash }}" }}"
            }[5m]))
            /
            sum(rate(http_requests_total{
              app="{{ .Release.Name }}",
              rollouts_pod_template_hash="{{ "{{ args.canary-hash }}" }}"
            }[5m]))
