apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    release: kube-prometheus-stack   # must match Prometheus operator's selector
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  targetLabels:
    - rollouts-pod-template-hash
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
