apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zero-drift-apps-dev
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - service: backend-service
          - service: frontend-service
  template:
    metadata:
      name: '{{.service}}-dev'
    spec:
      project: zero-drift
      source:
        repoURL: "https://github.com/Codervanshaj/ZeroDrift-K8-Pipeline.git"
        targetRevision: main
        path: 'helm/{{.service}}'
        helm:
          valueFiles:
            - values.yaml
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: zero-drift-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zero-drift-apps-prod
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - service: backend-service
          - service: frontend-service
  template:
    metadata:
      name: '{{.service}}-prod'
    spec:
      project: zero-drift
      source:
        repoURL: "https://github.com/Codervanshaj/ZeroDrift-K8-Pipeline.git"
        targetRevision: main
        path: 'helm/{{.service}}'
        helm:
          valueFiles:
            - values.yaml
            - values-prod.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: zero-drift-prod
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
