apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zero-drift-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: backend-service
                  port: "3000"
                - service: frontend-service
                  port: "8080"
          - list:
              elements:
                - env: dev
                  namespace: zero-drift-dev
                  autoSync: "true"
                  valuesFile: values-dev.yaml
                - env: prod
                  namespace: zero-drift-prod
                  autoSync: "false"
                  valuesFile: values-prod.yaml
  template:
    metadata:
      name: '{{.service}}-{{.env}}'
    spec:
      project: zero-drift
      source:
        repoURL: "https://github.com/Codervanshaj/ZeroDrift-K8-Pipeline.git"
        targetRevision: main
        path: 'helm/{{.service}}'
        helm:
          valueFiles:
            - values.yaml
            - '{{.valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        {{if eq .autoSync "true"}}
        automated:
          prune: true
          selfHeal: true
        {{end}}
        syncOptions:
          - CreateNamespace=true
