apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: argocd
spec:
  project: zero-drift
  source:
    repoURL: "https://github.com/Codervanshaj/ZeroDrift-K8-Pipeline.git"
    targetRevision: main
    path: argocd/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
