apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: zero-drift
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/Codervanshaj/ZeroDrift-K8-Pipeline.git"
    - "https://prometheus-community.github.io/helm-charts"   # allow infra charts
    - "https://argoproj.github.io/argo-helm"
    - "https://grafana.github.io/helm-charts"
    - "https://kyverno.github.io/kyverno/"
    - "https://charts.chaos-mesh.org"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: readonly
      policies:
        - p, proj:zero-drift:readonly, applications, get, zero-drift/*, allow
