apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    slack-token: AgB... # (Dummy encrypted data)
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
