apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    admin-user: AgAxyz... # (Dummy encrypted data)
    admin-password: AgAabc... # (Dummy encrypted data)
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
