---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: default
spec:
  encryptedData:
    admin-password: AgBv/9+Jn2LWY8n6/1Tw0YN8izuOcP9vvxXkm4Bj+rtB/cOM6IogO6supBI3QeOGfia0DdZytGjc8cBYEUfN31MD2qqVwFc5dLTmmRNFL3rVmrctACvzuJ6GS72HcZJVWHiwZqQgwUdIGmeM1McRe6gxPcM/qDzXppw9atJ1Q4tngMCCSaW56EbcwEPnr11pe1FHkaFfdXXqKHOhHSZOw3jW860lbSCv3aC71p2z5nAHwdH07xxmCNEemNPnrpuiTE1Qbx0fWIXaDFAZwzmqssyQGkDudilsQDIhJiawpmG8ShPRdordU0o1xtaw/IFVzcCjFi9sklcPzmttAyTM+XeJmXec9t/Ayppae0N/bk4FOJOySwbyTTMRKVY0qHTlSD+T9o6GRFnTgfJKfmLK3v8ULWCfeZSDNUwGZh/JN83Q0BSA/hnhbpw9e1RW0UMgauI5ZNC86wSLQ2sAe6RPhbR4eATy8Una6QdE2/VlJbwjCsinMmOKKDRprhLDZAxH8w6jquKMDPuUe713WcJLDOp+TnTh5w32oFh4Ke1tR0HE4XFCSDXi2OaWVOaoptqdAR1RgJ/roph1y+ekxA41DMZhvTueajzZE860cO1mZea+9Lil2ZVBUiPCERzeNgEDnQFLoXIhxkLiQDY7EcUhzRNKIMsPgrCbsqY7dJvNh/f2sh0RpeveHYk8e3ZC3BkyRmXedCdZU2l0rPpGeA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: default
